FROM java

ADD https://github.com/quantifind/KafkaOffsetMonitor/releases/download/v0.2.1/KafkaOffsetMonitor-assembly-0.2.1.jar /

ADD start-kafka-monitor.sh /start-kafka-monitor.sh

CMD /start-kafka-monitor.sh
